//Jenkinsfile (Declarative Pipeline)
pipeline {
    agent any
    stages {
        /* "Build" and "Test" stages omitted */

        stage('Deploy - Staging') {
            steps {
                dir ('jenkins-as-container/projects') {
                    sh './deploy staging'
                    sh './deploy run-smoke-tests'
                }
            }
        }

        stage('Sanity check') {
            steps {
                input "Does the staging environment look ok?"
            }
        }

        stage('Deploy - Production') {
            steps {
                dir ('jenkins-as-container/projects') {
                    sh './deploy production'
                }
            }
        }
    }
}