//Jenkinsfile (Declarative Pipeline)
pipeline {
    agent any
    stages {
        /* "Build" and "Test" stages omitted */

        stage('Deploy - Staging') {
            steps {
                sh 'cd jenkins-as-container/projects'
                sh './jenkins-as-container/projects/deploy staging'
                //sh './deploy.sh run-smoke-tests'
                //sh 'pwd'
            }
        }

        stage('Sanity check') {
            steps {
                input "Does the staging environment look ok?"
            }
        }

        stage('Deploy - Production') {
            steps {
                sh 'cd jenkins-as-container/projects'
                //sh './deploy.sh production'
            }
        }
    }
}