//Jenkinsfile (Declarative Pipeline)
pipeline {
    agent any
    stages {
        /* "Build" and "Test" stages omitted */
        dir ('jenkins-as-container/projects') {
            stage('Deploy - Staging') {
                steps {
                    sh './../deploy staging'
                    sh './../deploy run-smoke-tests'
                }
            }

            stage('Sanity check') {
                steps {
                    input "Does the staging environment look ok?"
                }
            }

            stage('Deploy - Production') {
                steps {
                    sh './../deploy production'
                }
            }
        }
    }
}